import { Event, EventCategory, Registration, Certificate, UserDashboard } from '../types/database';

// Event Categories
export const categories: EventCategory[] = [
  {
    id: 'tech',
    name: 'Technology',
    description: 'Tech talks, workshops, and coding events',
    color: '#2196F3',
    icon: 'laptop',
    sortOrder: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'business',
    name: 'Business',
    description: 'Entrepreneurship, startups, and business networking',
    color: '#4CAF50',
    icon: 'briefcase',
    sortOrder: 2,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'design',
    name: 'Design',
    description: 'UI/UX design, graphics, and creative workshops',
    color: '#FF9800',
    icon: 'palette',
    sortOrder: 3,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sports',
    name: 'Sports',
    description: 'Athletic events, tournaments, and fitness',
    color: '#F44336',
    icon: 'football',
    sortOrder: 4,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'culture',
    name: 'Culture',
    description: 'Arts, music, dance, and cultural celebrations',
    color: '#9C27B0',
    icon: 'music',
    sortOrder: 5,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'academic',
    name: 'Academic',
    description: 'Lectures, seminars, and educational workshops',
    color: '#607D8B',
    icon: 'school',
    sortOrder: 6,
    active: true,
    createdAt: new Date().toISOString(),
  },
];

// Enhanced Events
export const events: Event[] = [
  {
    id: '1',
    title: 'React Native Workshop 2024',
    description: 'Master mobile app development with React Native. Learn from industry experts and build your first cross-platform app.',
    shortDescription: 'Master mobile app development with React Native',
    status: 'published',
    visibility: 'public',
    categoryId: 'tech',
    startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    registrationStart: new Date().toISOString(),
    registrationEnd: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: 'UTC',
    locationType: 'physical',
    venue: 'Tech Hub, Building A, Room 101',
    maxParticipants: 50,
    minParticipants: 10,
    currentRegistrations: 35,
    waitlistEnabled: true,
    requiresApproval: false,
    requiresPayment: true,
    paymentAmount: 299,
    prerequisites: ['Basic JavaScript knowledge', 'Laptop with Node.js installed'],
    bannerImageUrl: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500',
    galleryImages: [],
    documents: [],
    allowCancellation: true,
    sendReminders: true,
    collectFeedback: true,
    generateCertificates: true,
    viewsCount: 245,
    featured: true,
    tags: ['React Native', 'Mobile Development', 'Workshop', 'Cross-platform'],
    createdBy: 'org1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Annual Tech Summit 2024',
    description: 'Join industry leaders for a day of innovation, networking, and insights into the future of technology.',
    shortDescription: 'Join industry leaders for innovation and networking',
    status: 'published',
    visibility: 'public',
    categoryId: 'tech',
    startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000).toISOString(),
    registrationStart: new Date().toISOString(),
    registrationEnd: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: 'UTC',
    locationType: 'physical',
    venue: 'Convention Center, Hall A',
    maxParticipants: 500,
    minParticipants: 50,
    currentRegistrations: 423,
    waitlistEnabled: true,
    requiresApproval: false,
    requiresPayment: true,
    paymentAmount: 1999,
    prerequisites: ['Professional attire recommended'],
    bannerImageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=500',
    galleryImages: [],
    documents: [],
    allowCancellation: true,
    sendReminders: true,
    collectFeedback: true,
    generateCertificates: true,
    viewsCount: 1234,
    featured: true,
    tags: ['Conference', 'Technology', 'Innovation', 'Networking'],
    createdBy: 'org2',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'UI/UX Design Masterclass',
    description: 'Elevate your design skills with this intensive masterclass covering modern design principles.',
    shortDescription: 'Elevate your design skills with modern principles',
    status: 'published',
    visibility: 'public',
    categoryId: 'design',
    startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
    registrationStart: new Date().toISOString(),
    registrationEnd: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: 'UTC',
    locationType: 'physical',
    venue: 'Design Studio, Creative Campus',
    maxParticipants: 30,
    minParticipants: 5,
    currentRegistrations: 18,
    waitlistEnabled: false,
    requiresApproval: true,
    requiresPayment: true,
    paymentAmount: 899,
    prerequisites: ['Figma account', 'Design portfolio (optional)'],
    bannerImageUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=500',
    galleryImages: [],
    documents: [],
    allowCancellation: true,
    sendReminders: true,
    collectFeedback: true,
    generateCertificates: true,
    viewsCount: 567,
    featured: false,
    tags: ['UI/UX', 'Design', 'Figma', 'User Research'],
    createdBy: 'org3',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Startup Pitch Night',
    description: 'Watch promising startups pitch their ideas to a panel of investors and industry experts.',
    shortDescription: 'Watch startups pitch to investors and experts',
    status: 'published',
    visibility: 'public',
    categoryId: 'business',
    startDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
    registrationStart: new Date().toISOString(),
    registrationEnd: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: 'UTC',
    locationType: 'physical',
    venue: 'Innovation Hub, Auditorium',
    maxParticipants: 200,
    minParticipants: 20,
    currentRegistrations: 156,
    waitlistEnabled: true,
    requiresApproval: false,
    requiresPayment: false,
    prerequisites: ['None'],
    bannerImageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=500',
    galleryImages: [],
    documents: [],
    allowCancellation: true,
    sendReminders: true,
    collectFeedback: true,
    generateCertificates: false,
    viewsCount: 890,
    featured: true,
    tags: ['Startup', 'Pitch', 'Investment', 'Networking'],
    createdBy: 'org4',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Campus Music Festival',
    description: 'Annual music festival featuring student bands, local artists, and special guests.',
    shortDescription: 'Annual music festival with bands and activities',
    status: 'published',
    visibility: 'public',
    categoryId: 'culture',
    startDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000 + 10 * 60 * 60 * 1000).toISOString(),
    registrationStart: new Date().toISOString(),
    registrationEnd: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: 'UTC',
    locationType: 'physical',
    venue: 'Campus Green, Outdoor Stage',
    maxParticipants: 1000,
    minParticipants: 100,
    currentRegistrations: 678,
    waitlistEnabled: true,
    requiresApproval: false,
    requiresPayment: true,
    paymentAmount: 299,
    prerequisites: ['Valid student ID for student discount'],
    bannerImageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=500',
    galleryImages: [],
    documents: [],
    allowCancellation: true,
    sendReminders: true,
    collectFeedback: true,
    generateCertificates: false,
    viewsCount: 2456,
    featured: true,
    tags: ['Music', 'Festival', 'Live Performance', 'Entertainment'],
    createdBy: 'org5',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Machine Learning Bootcamp',
    description: 'Intensive 3-day bootcamp covering machine learning fundamentals and practical applications.',
    shortDescription: 'Intensive ML bootcamp with practical applications',
    status: 'completed',
    visibility: 'public',
    categoryId: 'tech',
    startDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 3 * 24 * 60 * 60 * 1000).toISOString(),
    registrationStart: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    registrationEnd: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: 'UTC',
    locationType: 'physical',
    venue: 'Computer Lab, Building B',
    maxParticipants: 40,
    minParticipants: 10,
    currentRegistrations: 40,
    waitlistEnabled: false,
    requiresApproval: true,
    requiresPayment: true,
    paymentAmount: 1499,
    prerequisites: ['Python knowledge', 'Jupyter Notebook setup'],
    bannerImageUrl: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=500',
    galleryImages: [],
    documents: [],
    allowCancellation: false,
    sendReminders: true,
    collectFeedback: true,
    generateCertificates: true,
    viewsCount: 156,
    featured: false,
    tags: ['Machine Learning', 'Python', 'Data Science', 'AI'],
    createdBy: 'org6',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// User Registrations
export const registrations: Registration[] = [
  {
    id: 'reg1',
    eventId: '1',
    userId: 'user1',
    status: 'confirmed',
    registrationType: 'regular',
    requiresApproval: false,
    paymentStatus: 'completed',
    paymentAmount: 299,
    checkedIn: false,
    registrationData: { notes: 'Excited to learn React Native!' },
    confirmationSent: true,
    reminderSent: false,
    registeredAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'reg2',
    eventId: '6',
    userId: 'user1',
    status: 'confirmed',
    registrationType: 'regular',
    requiresApproval: true,
    approvedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    paymentStatus: 'completed',
    paymentAmount: 1499,
    checkedIn: true,
    checkInTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    registrationData: { experience: 'Intermediate Python' },
    confirmationSent: true,
    reminderSent: true,
    registeredAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'reg3',
    eventId: '3',
    userId: 'user1',
    status: 'waitlisted',
    registrationType: 'waitlist',
    requiresApproval: true,
    paymentStatus: 'pending',
    paymentAmount: 899,
    checkedIn: false,
    registrationData: { portfolio: 'https://myportfolio.com' },
    confirmationSent: false,
    reminderSent: false,
    registeredAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// User Dashboard Data
export const userDashboards: UserDashboard[] = [
  {
    id: 'user1',
    name: 'John Doe',
    email: 'john.doe@university.edu',
    role: 'student',
    totalRegistrations: 3,
    eventsAttended: 1,
    certificatesEarned: 1,
    achievementsEarned: 2,
  },
];

// Certificates
export const certificates: Certificate[] = [
  {
    id: 'cert-001',
    userId: 'user-001',
    eventId: 'evt-002',
    templateId: 'template1',
    certificateNumber: 'CERT-RN-2024-001',
    title: 'Certificate of Completion - React Native Workshop',
    content: 'This certifies that John Doe has successfully completed the React Native Workshop.',
    status: 'generated',
    generatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    verificationCode: 'RN24-VER-789ABC',
    verificationUrl: 'https://verify.eventhub.com/cert/RN24-VER-789ABC',
    verifiedCount: 3,
    metadata: {
      grade: 'A',
      instructor: 'Sarah Johnson',
      duration: '8 hours',
      modules: ['React Native Basics', 'Navigation', 'State Management', 'API Integration', 'Testing'],
      finalProject: 'E-commerce Mobile App',
      skills: ['React Native', 'TypeScript', 'Redux', 'React Navigation'],
      completionRate: '100%'
    },
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cert-002',
    userId: 'user-001',
    eventId: 'evt-003',
    templateId: 'template2',
    certificateNumber: 'CERT-TIS-2024-002',
    title: 'Certificate of Participation - Tech Innovation Summit',
    content: 'This certifies that John Doe participated in the Tech Innovation Summit.',
    status: 'generated',
    generatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    verificationCode: 'TIS24-VER-456DEF',
    verificationUrl: 'https://verify.eventhub.com/cert/TIS24-VER-456DEF',
    verifiedCount: 1,
    metadata: {
      type: 'participation',
      sessions: 6,
      speakers: ['John Doe', 'Jane Smith', 'Alex Brown'],
      duration: '3 days',
      topics: ['AI & Machine Learning', 'Blockchain', 'IoT', 'Cybersecurity'],
      networking: 'Premium access'
    },
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cert-003',
    userId: 'user-001',
    eventId: 'evt-005',
    templateId: 'template3',
    certificateNumber: 'CERT-JS-2024-003',
    title: 'Certificate of Achievement - Advanced JavaScript',
    content: 'This certifies that John Doe has achieved excellence in the Advanced JavaScript course.',
    status: 'generated',
    generatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    verificationCode: 'JS24-VER-123GHI',
    verificationUrl: 'https://verify.eventhub.com/cert/JS24-VER-123GHI',
    verifiedCount: 7,
    metadata: {
      grade: 'A+',
      instructor: 'Michael Chen',
      duration: '12 hours',
      modules: ['ES6+ Features', 'Async Programming', 'Design Patterns', 'Testing', 'Performance'],
      finalProject: 'Full-Stack Web Application',
      skills: ['JavaScript', 'Node.js', 'Express', 'MongoDB', 'Jest'],
      completionRate: '100%',
      examScore: '95%'
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cert-004',
    userId: 'user-001',
    eventId: 'evt-001',
    templateId: 'template4',
    certificateNumber: 'CERT-SPC-2024-004',
    title: 'Certificate of Excellence - Startup Pitch Competition',
    content: 'This certifies that John Doe achieved 2nd Place in the Startup Pitch Competition.',
    status: 'generated',
    generatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    verificationCode: 'SPC24-VER-789JKL',
    verificationUrl: 'https://verify.eventhub.com/cert/SPC24-VER-789JKL',
    verifiedCount: 12,
    metadata: {
      type: 'competition',
      rank: '2nd Place',
      category: 'Tech Innovation',
      judges: ['Emily Davis', 'Robert Wilson', 'Lisa Garcia'],
      award: '$5,000 Prize',
      mentorship: '6 months included',
      skills: ['Pitching', 'Business Planning', 'Market Analysis', 'Financial Modeling']
    },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Combined mock data
export const mockEnhancedData = {
  events,
  categories,
  registrations,
  userDashboards,
  certificates,
};
